import { NodeDefinition, NodeKind } from "@/types/zales";

/** Known OpenAI-compatible endpoints — picking one from the "Provider"
 *  dropdown on an AI node auto-fills the Base URL field. "Custom" leaves
 *  Base URL alone so any other OpenAI-compatible server works too
 *  (LM Studio, vLLM, a self-hosted 9Router instance at a different port,
 *  your own proxy, etc). */
export const PROVIDER_PRESETS: Record<string, { label: string; baseUrl: string; note?: string }> = {
  openai: { label: "OpenAI", baseUrl: "https://api.openai.com/v1" },
  openrouter: { label: "OpenRouter", baseUrl: "https://openrouter.ai/api/v1" },
  ninerouter: {
    label: "9Router (self-hosted, gratis/multi-provider)",
    baseUrl: "http://localhost:20128/v1",
    note: "Jalanin `npx 9router` dulu (atau di server kamu), baru isi API key dari dashboard-nya.",
  },
  gemini: {
    label: "Google Gemini (OpenAI-compatible)",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
  },
  groq: { label: "Groq (gratis, cepat)", baseUrl: "https://api.groq.com/openai/v1" },
  ollama: { label: "Ollama (lokal)", baseUrl: "http://localhost:11434/v1" },
  custom: { label: "Custom / lainnya", baseUrl: "" },
};

export const NODE_REGISTRY: Record<NodeKind, NodeDefinition> = {
  "trigger.manual": {
    kind: "trigger.manual",
    category: "trigger",
    label: "Manual Trigger",
    description: "Start the workflow manually",
    icon: "Play",
    hasInput: false,
    hasOutput: true,
    params: [],
  },
  "trigger.schedule": {
    kind: "trigger.schedule",
    category: "trigger",
    label: "Schedule",
    description: "Run on a cron schedule",
    icon: "Clock",
    hasInput: false,
    hasOutput: true,
    params: [
      {
        key: "cron",
        label: "Cron Expression",
        type: "text",
        placeholder: "*/15 * * * *",
        defaultValue: "*/15 * * * *",
      },
    ],
  },
  "trigger.webhook": {
    kind: "trigger.webhook",
    category: "trigger",
    label: "Webhook",
    description: "Trigger from an incoming HTTP request",
    icon: "Webhook",
    hasInput: false,
    hasOutput: true,
    params: [
      {
        key: "path",
        label: "Path",
        type: "text",
        placeholder: "/webhook/my-flow",
        defaultValue: "/webhook/my-flow",
      },
      {
        key: "method",
        label: "Method",
        type: "select",
        options: [
          { label: "POST", value: "POST" },
          { label: "GET", value: "GET" },
        ],
        defaultValue: "POST",
      },
    ],
  },
  "trigger.email": {
    kind: "trigger.email",
    category: "trigger",
    label: "Email (IMAP)",
    description: "Trigger when a new email arrives",
    icon: "Mail",
    hasInput: false,
    hasOutput: true,
    params: [
      { key: "host", label: "IMAP Host", type: "text", placeholder: "imap.gmail.com" },
      { key: "user", label: "Username", type: "text" },
      { key: "password", label: "Password", type: "password" },
      { key: "folder", label: "Folder", type: "text", defaultValue: "INBOX" },
    ],
  },
  "trigger.social_message": {
    kind: "trigger.social_message",
    category: "trigger",
    label: "Instagram/FB Message",
    description: "Trigger when a DM comes in on your connected Instagram or Facebook Page",
    icon: "MessageSquare",
    hasInput: false,
    hasOutput: true,
    params: [
      {
        key: "pageId",
        label: "Page/IG Account ID (opsional)",
        type: "text",
        placeholder: "kosongkan = dari akun manapun yang tersambung",
      },
      { key: "keyword", label: "Keyword (opsional)", type: "text" },
    ],
  },
  "trigger.whatsapp_gateway": {
    kind: "trigger.whatsapp_gateway",
    category: "trigger",
    label: "WhatsApp Gateway (RapidAPI)",
    description: "Trigger from an incoming-message webhook sent by a third-party WA gateway (RapidAPI, Whapi.cloud, etc) — supports text, images, videos, documents. Untuk WhatsApp resmi dari Meta, pakai node 'WhatsApp Cloud API (Meta)'.",
    icon: "Webhook",
    hasInput: false,
    hasOutput: true,
    params: [
      {
        key: "senderField",
        label: "Field path buat nomor pengirim",
        type: "text",
        placeholder: "from",
        defaultValue: "from",
      },
      {
        key: "textField",
        label: "Field path buat isi pesan",
        type: "text",
        placeholder: "message",
        defaultValue: "message",
      },
      {
        key: "mediaUrlField",
        label: "Field path buat URL media (opsional)",
        type: "text",
        placeholder: "mediaUrl / media.url / attachment.url",
        defaultValue: "mediaUrl",
      },
      {
        key: "mediaTypeField",
        label: "Field path buat tipe media (opsional)",
        type: "text",
        placeholder: "mediaType / media.type / attachment.mimetype",
        defaultValue: "mediaType",
      },
      { key: "keyword", label: "Keyword (opsional)", type: "text" },
    ],
  },
  "trigger.chat": {
    kind: "trigger.chat",
    category: "trigger",
    label: "Chat Box",
    description:
      "Trigger dari halaman Chat AI (/chat) di dalam Zales — pesan & file yang diketik user di situ langsung memicu workflow ini. Pasangannya adalah node 'Balas ke Chat' buat ngirim jawaban balik ke chat box.",
    icon: "MessageSquare",
    hasInput: false,
    hasOutput: true,
    params: [{ key: "keyword", label: "Keyword (opsional)", type: "text" }],
  },
  "trigger.whatsapp_meta": {
    kind: "trigger.whatsapp_meta",
    category: "trigger",
    label: "WhatsApp Cloud API (Meta)",
    description:
      "Trigger dari webhook resmi Meta WhatsApp Business Platform (developers.facebook.com) — pasang Callback URL /api/webhooks/whatsapp-meta dan Verify Token di Meta App dashboard. Payload sudah otomatis di-parse sesuai format resmi Meta.",
    icon: "MessageCircle",
    hasInput: false,
    hasOutput: true,
    params: [
      { key: "keyword", label: "Keyword (opsional)", type: "text" },
      {
        key: "phoneNumberIdFilter",
        label: "Hanya proses dari Phone Number ID ini (opsional)",
        type: "text",
        placeholder: "kosongin kalau cuma punya 1 nomor WA Business",
      },
    ],
  },
  "ai.agent": {
    kind: "ai.agent",
    category: "ai",
    label: "AI Agent",
    description: "LLM agent that can decide on its own to call attached tools or sub-agents (real tool-calling, not a static chain)",
    icon: "Bot",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "provider",
        label: "Provider",
        type: "select",
        options: Object.entries(PROVIDER_PRESETS).map(([value, p]) => ({ label: p.label, value })),
        defaultValue: "ollama",
      },
      {
        key: "baseUrl",
        label: "API Endpoint",
        type: "text",
        placeholder: "http://localhost:11434/v1",
        defaultValue: "http://localhost:11434/v1",
      },
      {
        key: "model",
        label: "Model Name",
        type: "text",
        placeholder: "hermes-3",
        defaultValue: "llama3:8b",
      },
      { key: "apiKey", label: "API Key", type: "password", placeholder: "Optional for cloud providers" },
      {
        key: "systemPrompt",
        label: "System Prompt",
        type: "textarea",
        placeholder: "You are a helpful assistant...",
        defaultValue: "You are a helpful assistant.",
      },
      {
        key: "userMessage",
        label: "User Message Template",
        type: "textarea",
        placeholder: "{{input.text}}",
        defaultValue: "{{input.text}}",
      },
      {
        key: "attachedTools",
        label: "Tools & Sub-agents",
        type: "node_multiselect",
        defaultValue: [],
      },
      {
        key: "maxToolIterations",
        label: "Max Tool Calls per Run",
        type: "number",
        min: 1,
        max: 10,
        defaultValue: 4,
      },
      { key: "temperature", label: "Temperature", type: "slider", min: 0, max: 2, step: 0.1, defaultValue: 0.7 },
      { key: "topP", label: "Top P", type: "slider", min: 0, max: 1, step: 0.05, defaultValue: 1 },
      { key: "maxTokens", label: "Max Tokens", type: "number", min: 1, max: 32000, defaultValue: 1024 },
    ],
  },
  "ai.chat": {
    kind: "ai.chat",
    category: "ai",
    label: "Chat Model",
    description: "Simple single-turn chat completion",
    icon: "MessageSquare",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "provider",
        label: "Provider",
        type: "select",
        options: Object.entries(PROVIDER_PRESETS).map(([value, p]) => ({ label: p.label, value })),
        defaultValue: "ollama",
      },
      { key: "baseUrl", label: "API Endpoint", type: "text", defaultValue: "http://localhost:11434/v1" },
      { key: "model", label: "Model Name", type: "text", defaultValue: "mistral" },
      { key: "apiKey", label: "API Key", type: "password" },
      { key: "prompt", label: "Prompt Template", type: "textarea", placeholder: "{{input}}" },
    ],
  },
  "ai.image": {
    kind: "ai.image",
    category: "ai",
    label: "AI Image (Gemini)",
    description: "Generate an image from a text prompt using Gemini",
    icon: "Image",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "apiKey", label: "Gemini API Key", type: "password", placeholder: "AIza..." },
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [
          { label: "gemini-2.5-flash-image", value: "gemini-2.5-flash-image" },
          { label: "imagen-4.0-generate-001", value: "imagen-4.0-generate-001" },
        ],
        defaultValue: "gemini-2.5-flash-image",
      },
      {
        key: "prompt",
        label: "Prompt",
        type: "textarea",
        placeholder: "Foto produk minimalis di atas meja kayu, {{input.text}}",
      },
    ],
  },
  "ai.vision": {
    kind: "ai.vision",
    category: "ai",
    label: "AI Vision (Gemini)",
    description:
      "Analisa isi gambar ATAU VIDEO pakai Gemini native API — beda dari 'AI Agent' biasa (OpenAI-compatible) yang cuma baca gambar, node ini beneran bisa 'nonton' isi video yang diupload user (dari trigger Chat Box) dan menjelaskannya. Cocok dipasang langsung setelah Chat Trigger, atau di-attach sebagai tool ke AI Agent lain.",
    icon: "Eye",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "apiKey", label: "Gemini API Key", type: "password", placeholder: "AIza..." },
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [
          { label: "gemini-2.5-flash", value: "gemini-2.5-flash" },
          { label: "gemini-2.5-pro", value: "gemini-2.5-pro" },
        ],
        defaultValue: "gemini-2.5-flash",
      },
      {
        key: "prompt",
        label: "Prompt / Pertanyaan",
        type: "textarea",
        placeholder: "{{input.text}}",
        defaultValue: "{{input.text}}",
      },
    ],
  },
  "ai.video": {
    kind: "ai.video",
    category: "ai",
    label: "AI Video (Veo)",
    description: "Generate a short video from a text prompt using Gemini Veo (paid, async — bisa makan waktu beberapa menit)",
    icon: "Video",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "apiKey", label: "Gemini API Key", type: "password", placeholder: "AIza..." },
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [{ label: "veo-3.0-generate-001", value: "veo-3.0-generate-001" }],
        defaultValue: "veo-3.0-generate-001",
      },
      { key: "prompt", label: "Prompt", type: "textarea", placeholder: "{{input.text}}" },
      {
        key: "maxWaitSeconds",
        label: "Max Wait (detik)",
        type: "number",
        min: 30,
        max: 600,
        defaultValue: 300,
      },
    ],
  },
  "ai.memory": {
    kind: "ai.memory",
    category: "memory",
    label: "Buffer Memory",
    description: "Stores conversation history for an agent",
    icon: "Brain",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "windowSize", label: "History Window", type: "number", min: 1, max: 100, defaultValue: 10 },
    ],
  },
  "ai.tool": {
    kind: "ai.tool",
    category: "ai",
    label: "MCP Connector",
    description: "Connect to any MCP server (Notion, Slack, GitHub, Zapier MCP, your own, etc.) and call one of its tools",
    icon: "Plug",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "serverUrl",
        label: "MCP Server URL",
        type: "text",
        placeholder: "https://mcp.example.com/sse atau /mcp",
      },
      { key: "authToken", label: "Auth Token (opsional)", type: "password" },
      {
        key: "toolName",
        label: "Tool Name",
        type: "text",
        placeholder: "isi setelah klik \"List tools\" di Test node, atau lihat dokumentasi server-nya",
      },
      {
        key: "argsJson",
        label: "Tool Arguments (JSON)",
        type: "code",
        placeholder: '{\n  "query": "{{input.text}}"\n}',
        defaultValue: "{}",
      },
    ],
  },
  "integration.sheets": {
    kind: "integration.sheets",
    category: "integration",
    label: "Google Sheets",
    description: "Read or write rows to a spreadsheet",
    icon: "Sheet",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "spreadsheetId", label: "Spreadsheet ID", type: "text" },
      {
        key: "operation",
        label: "Operation",
        type: "select",
        options: [
          { label: "Read rows", value: "read" },
          { label: "Append row", value: "append" },
        ],
        defaultValue: "read",
      },
      { key: "range", label: "Range", type: "text", placeholder: "Sheet1!A1:D10" },
    ],
  },
  "integration.telegram": {
    kind: "integration.telegram",
    category: "integration",
    label: "Telegram",
    description: "Send a message via Telegram bot",
    icon: "Send",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "botToken", label: "Bot Token", type: "password" },
      { key: "chatId", label: "Chat ID", type: "text" },
      { key: "message", label: "Message", type: "textarea", placeholder: "{{input}}" },
    ],
  },
  "integration.social_reply": {
    kind: "integration.social_reply",
    category: "integration",
    label: "Reply on Instagram/FB",
    description: "Send a DM reply back on Instagram or Facebook Messenger",
    icon: "Reply",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "accessToken", label: "Page Access Token", type: "password" },
      {
        key: "recipientId",
        label: "Recipient ID",
        type: "text",
        placeholder: '{{nodes["Instagram/FB Message"].from}}',
      },
      { key: "message", label: "Message", type: "textarea", placeholder: "{{input.text}}" },
    ],
  },
  "integration.leadfinder": {
    kind: "integration.leadfinder",
    category: "integration",
    label: "Lead Finder (Google Places)",
    description: "Find businesses via the official Google Places API and flag which ones have no website — output only, no auto-messaging",
    icon: "MapPin",
    hasInput: false,
    hasOutput: true,
    params: [
      { key: "apiKey", label: "Google Places API Key", type: "password" },
      {
        key: "query",
        label: "Cari apa & di mana",
        type: "text",
        placeholder: "toko kue di Jakarta Selatan",
      },
      { key: "maxResults", label: "Jumlah maksimal hasil", type: "number", min: 1, max: 60, defaultValue: 20 },
      {
        key: "onlyMissingWebsite",
        label: "Filter",
        type: "select",
        options: [
          { label: "Cuma yang belum punya website", value: "yes" },
          { label: "Semua hasil", value: "no" },
        ],
        defaultValue: "yes",
      },
    ],
  },
  "integration.social": {
    kind: "integration.social",
    category: "integration",
    label: "Social Media Post",
    description: "Post caption + media to a social platform (or export for manual upload)",
    icon: "Share2",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { label: "Instagram (Graph API)", value: "instagram" },
          { label: "Facebook Page (Graph API)", value: "facebook" },
          { label: "TikTok (belum ada API resmi tersambung)", value: "tiktok" },
          { label: "Manual export (semua platform)", value: "manual" },
        ],
        defaultValue: "manual",
      },
      { key: "caption", label: "Caption", type: "textarea", placeholder: "{{input.text}}" },
      { key: "mediaUrl", label: "Media URL (opsional kalau pakai imageBase64 dari node sebelumnya)", type: "text" },
      { key: "accessToken", label: "Access Token", type: "password" },
      { key: "accountId", label: "Page / IG Business Account ID", type: "text" },
    ],
  },
  "integration.slack": {
    kind: "integration.slack",
    category: "integration",
    label: "Slack",
    description: "Send a message to a Slack channel via an Incoming Webhook URL",
    icon: "Hash",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "webhookUrl",
        label: "Incoming Webhook URL",
        type: "password",
        placeholder: "https://hooks.slack.com/services/...",
      },
      { key: "message", label: "Message", type: "textarea", placeholder: "{{input.text}}" },
    ],
  },
  "integration.discord": {
    kind: "integration.discord",
    category: "integration",
    label: "Discord",
    description: "Send a message to a Discord channel via a Webhook URL",
    icon: "MessageCircle",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "webhookUrl",
        label: "Discord Webhook URL",
        type: "password",
        placeholder: "https://discord.com/api/webhooks/...",
      },
      { key: "message", label: "Message", type: "textarea", placeholder: "{{input.text}}" },
    ],
  },
  "integration.notion": {
    kind: "integration.notion",
    category: "integration",
    label: "Notion",
    description: "Create a page in a Notion database via the Notion API",
    icon: "FileText",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "integrationToken", label: "Internal Integration Token", type: "password", placeholder: "secret_..." },
      { key: "databaseId", label: "Database ID", type: "text" },
      { key: "titlePropertyName", label: "Title Property Name", type: "text", defaultValue: "Name" },
      { key: "title", label: "Page Title", type: "text", placeholder: "{{input.text}}" },
      {
        key: "contentJson",
        label: "Extra Properties (JSON, opsional)",
        type: "code",
        placeholder: '{\n  "Status": { "select": { "name": "New" } }\n}',
        defaultValue: "{}",
      },
    ],
  },
  "integration.airtable": {
    kind: "integration.airtable",
    category: "integration",
    label: "Airtable",
    description: "Create a record in an Airtable table via a Personal Access Token",
    icon: "Table",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "accessToken", label: "Personal Access Token", type: "password", placeholder: "pat..." },
      { key: "baseId", label: "Base ID", type: "text", placeholder: "app..." },
      { key: "tableName", label: "Table Name", type: "text", placeholder: "Leads" },
      {
        key: "fieldsJson",
        label: "Fields (JSON)",
        type: "code",
        placeholder: '{\n  "Name": "{{input.text}}"\n}',
        defaultValue: "{}",
      },
    ],
  },
  "integration.email_send": {
    kind: "integration.email_send",
    category: "integration",
    label: "Send Email",
    description: "Send a transactional email via Resend",
    icon: "Mail",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "apiKey", label: "Resend API Key", type: "password", placeholder: "re_..." },
      { key: "from", label: "From", type: "text", placeholder: "Zales <noreply@yourdomain.com>" },
      { key: "to", label: "To", type: "text", placeholder: "{{input.email}}" },
      { key: "subject", label: "Subject", type: "text", placeholder: "{{input.subject}}" },
      { key: "body", label: "Body (HTML)", type: "textarea", placeholder: "<p>{{input.text}}</p>" },
    ],
  },
  "integration.twilio_sms": {
    kind: "integration.twilio_sms",
    category: "integration",
    label: "Twilio SMS",
    description: "Send an SMS via the Twilio REST API",
    icon: "Smartphone",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "accountSid", label: "Account SID", type: "text", placeholder: "AC..." },
      { key: "authToken", label: "Auth Token", type: "password" },
      { key: "fromNumber", label: "From Number", type: "text", placeholder: "+1415..." },
      { key: "toNumber", label: "To Number", type: "text", placeholder: "{{input.phone}}" },
      { key: "message", label: "Message", type: "textarea", placeholder: "{{input.text}}" },
    ],
  },
  "integration.whatsapp_reply": {
    kind: "integration.whatsapp_reply",
    category: "integration",
    label: "Send WhatsApp Reply",
    description:
      "Kirim balasan WhatsApp — default pakai Meta WhatsApp Cloud API resmi (developers.facebook.com), atau pilih RapidAPI kalau masih pakai gateway pihak ketiga lama.",
    icon: "MessageCircle",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "provider",
        label: "Provider",
        type: "select",
        options: [
          { label: "Meta WhatsApp Cloud API (resmi)", value: "meta" },
          { label: "RapidAPI (pihak ketiga)", value: "rapidapi" },
        ],
        defaultValue: "meta",
      },
      {
        key: "toNumber",
        label: "Nomor Tujuan",
        type: "text",
        placeholder: '{{nodes["WhatsApp Gateway"].from}}',
      },
      { key: "message", label: "Pesan Balasan", type: "textarea", placeholder: "{{input.text}}" },

      // --- Meta Cloud API fields (provider = "meta") ---
      {
        key: "metaAccessToken",
        label: "[Meta] Access Token (kosongin = pakai dari Pengaturan Akun)",
        type: "password",
        placeholder: "Temporary (24 jam) atau Permanent (System User) token",
      },
      {
        key: "metaPhoneNumberId",
        label: "[Meta] Phone Number ID (kosongin = pakai dari Pengaturan Akun)",
        type: "text",
        placeholder: "1234567890 — dari Meta App > WhatsApp > API Setup",
      },

      // --- RapidAPI fields (provider = "rapidapi", legacy) ---
      {
        key: "apiUrl",
        label: "[RapidAPI] Endpoint URL",
        type: "text",
        placeholder: "https://whatsapp-xyz.p.rapidapi.com/send-message",
      },
      { key: "rapidApiKey", label: "[RapidAPI] X-RapidAPI-Key", type: "password", placeholder: "..." },
      {
        key: "rapidApiHost",
        label: "[RapidAPI] X-RapidAPI-Host",
        type: "text",
        placeholder: "whatsapp-xyz.p.rapidapi.com",
      },
      {
        key: "bodyTemplateJson",
        label: "[RapidAPI] Body Request (JSON, opsional — override default)",
        type: "code",
        placeholder: '{\n  "phone": "{{nodes[\\"WhatsApp Gateway\\"].from}}",\n  "message": "{{input.text}}"\n}',
      },
    ],
  },
  "integration.google_maps_scraper": {
    kind: "integration.google_maps_scraper",
    category: "integration",
    label: "Google Maps Scraper",
    description:
      "Scrape data bisnis dari Google Maps via RapidAPI (Google Map Scraper) — cari tempat, detail satu tempat, atau auto-complete. Bisa di-attach ke AI Agent sebagai tool biar agent WA bisa cariin lokasi/toko sesuai chat.",
    icon: "MapPin",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "rapidApiKey",
        label: "X-RapidAPI-Key (kosongin = pakai dari Pengaturan Akun)",
        type: "password",
        placeholder: "...",
      },
      {
        key: "rapidApiHost",
        label: "X-RapidAPI-Host",
        type: "text",
        placeholder: "google-map-scraper1.p.rapidapi.com",
        defaultValue: "google-map-scraper1.p.rapidapi.com",
      },
      {
        key: "endpoint",
        label: "Endpoint",
        type: "select",
        options: [
          { label: "Search Places", value: "search" },
          { label: "Place Detail", value: "detail" },
          { label: "Auto-complete Search", value: "autocomplete" },
        ],
        defaultValue: "search",
      },
      {
        key: "query",
        label: "Query Pencarian",
        type: "text",
        placeholder: '{{input.text}} — misal "american restaurant new york"',
        defaultValue: "{{input.text}}",
      },
      {
        key: "placeId",
        label: "Place ID (khusus mode Place Detail)",
        type: "text",
        placeholder: '{{nodes["Google Maps Scraper"].data.results[0].id}}',
      },
      {
        key: "lat",
        label: "Latitude (opsional)",
        type: "text",
        placeholder: "40.7128",
      },
      {
        key: "lng",
        label: "Longitude (opsional)",
        type: "text",
        placeholder: "-74.0060",
      },
      {
        key: "limit",
        label: "Jumlah Hasil (opsional)",
        type: "number",
        min: 1,
        max: 100,
        defaultValue: 20,
      },
      {
        key: "extraParamsJson",
        label: "Query Param Tambahan (JSON, opsional)",
        type: "code",
        placeholder: '{\n  "language": "id",\n  "zoom": "13"\n}',
      },
    ],
  },
  "integration.chat_reply": {
    kind: "integration.chat_reply",
    category: "integration",
    label: "Balas ke Chat",
    description:
      "Kirim balasan akhir yang ditampilkan di halaman Chat AI (/chat) — pasangan dari trigger 'Chat Box'. Taruh di ujung workflow setelah AI Agent/proses lain selesai, misal: \"Sudah saya generate gambarnya dan upload ke YouTube, ini hasilnya: ...\"",
    icon: "MessageSquare",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "message",
        label: "Pesan Balasan",
        type: "textarea",
        placeholder: '{{nodes["AI Agent"].text}}',
        defaultValue: "{{input.text}}",
      },
    ],
  },
  "integration.youtube_upload": {
    kind: "integration.youtube_upload",
    category: "integration",
    label: "Upload ke YouTube",
    description:
      "Upload video ke YouTube pakai YouTube Data API v3 (resumable upload). Butuh OAuth Client ID/Secret + Refresh Token dari Google Cloud Console (scope: youtube.upload). Video bisa dari hasil node 'AI Video (Veo)' ({{nodes[\"Video Generator\"].videoUri}}) atau file yang diupload user lewat Chat Box ({{input.files[0]}}).",
    icon: "Youtube",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "clientId", label: "OAuth Client ID", type: "password", placeholder: "....apps.googleusercontent.com" },
      { key: "clientSecret", label: "OAuth Client Secret", type: "password", placeholder: "GOCSPX-..." },
      { key: "refreshToken", label: "Refresh Token", type: "password", placeholder: "1//..." },
      {
        key: "videoUrl",
        label: "URL Video (kalau video ada di URL publik, mis. hasil Veo)",
        type: "text",
        placeholder: '{{nodes["Video Generator"].videoUri}}',
      },
      {
        key: "videoFileFromInput",
        label: "Ambil video dari file upload trigger? (kosongin kalau pakai URL Video di atas)",
        type: "select",
        options: [
          { label: "Tidak — pakai URL Video", value: "no" },
          { label: "Ya — pakai file pertama dari input.files", value: "yes" },
        ],
        defaultValue: "no",
      },
      { key: "title", label: "Judul Video", type: "text", placeholder: "{{input.text}}" },
      { key: "description", label: "Deskripsi", type: "textarea" },
      { key: "tags", label: "Tags (pisah koma, opsional)", type: "text", placeholder: "ai, tutorial, zales" },
      {
        key: "privacyStatus",
        label: "Privasi",
        type: "select",
        options: [
          { label: "Public", value: "public" },
          { label: "Unlisted", value: "unlisted" },
          { label: "Private", value: "private" },
        ],
        defaultValue: "public",
      },
    ],
  },
  "integration.tiktok_upload": {
    kind: "integration.tiktok_upload",
    category: "integration",
    label: "Upload ke TikTok",
    description:
      "Upload video ke TikTok pakai TikTok Content Posting API v2. Butuh Access Token dari TikTok Developer Portal — akun harus sudah lolos App Review TikTok untuk publish ke akun publik (sebelum itu, cuma bisa ke sandbox/akun developer sendiri). Video bisa dari URL publik (mis. hasil 'AI Video (Veo)') atau file upload user lewat Chat Box.",
    icon: "Music2",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "accessToken", label: "Access Token", type: "password", placeholder: "act.xxxxx" },
      {
        key: "videoUrl",
        label: "URL Video (kalau video ada di URL publik, mis. hasil Veo)",
        type: "text",
        placeholder: '{{nodes["Video Generator"].videoUri}}',
      },
      {
        key: "videoFileFromInput",
        label: "Ambil video dari file upload trigger? (kosongin kalau pakai URL Video di atas)",
        type: "select",
        options: [
          { label: "Tidak — pakai URL Video", value: "no" },
          { label: "Ya — pakai file pertama dari input.files", value: "yes" },
        ],
        defaultValue: "no",
      },
      { key: "caption", label: "Caption", type: "textarea", placeholder: "{{input.text}}" },
      {
        key: "privacyLevel",
        label: "Privasi",
        type: "select",
        options: [
          { label: "Public (butuh App Review approved)", value: "PUBLIC_TO_EVERYONE" },
          { label: "Hanya Saya (sandbox/testing)", value: "SELF_ONLY" },
          { label: "Followers", value: "MUTUAL_FOLLOW_FRIENDS" },
        ],
        defaultValue: "SELF_ONLY",
      },
    ],
  },
  "integration.gamma_generate": {
    kind: "integration.gamma_generate",
    category: "integration",
    label: "Generate Presentasi (Gamma)",
    description:
      "Generate presentasi/dokumen/social post/webpage otomatis pakai Gamma API (gamma.app) dari teks — cocok buat 'buatkan PPT tentang X'. Butuh Gamma API Key (Account Settings > API Keys di gamma.app, minimal plan Pro). Prosesnya async: node ini otomatis polling sampai selesai lalu mengembalikan link Gamma (gammaUrl) dan link download file (exportUrl).",
    icon: "Presentation",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "apiKey", label: "Gamma API Key", type: "password", placeholder: "sk-gamma-..." },
      {
        key: "inputText",
        label: "Topik / Isi Konten",
        type: "textarea",
        placeholder: "{{input.text}}",
        defaultValue: "{{input.text}}",
      },
      { key: "title", label: "Judul (opsional)", type: "text", placeholder: "Kosongin = auto dari isi konten" },
      {
        key: "format",
        label: "Format Output",
        type: "select",
        options: [
          { label: "Presentasi (slide/PPT)", value: "presentation" },
          { label: "Dokumen", value: "document" },
          { label: "Social Post", value: "social" },
          { label: "Webpage", value: "webpage" },
        ],
        defaultValue: "presentation",
      },
      {
        key: "textMode",
        label: "Mode Teks",
        type: "select",
        options: [
          { label: "Generate — kembangkan dari topik singkat", value: "generate" },
          { label: "Condense — ringkas dari teks panjang", value: "condense" },
          { label: "Preserve — pertahankan teks apa adanya", value: "preserve" },
        ],
        defaultValue: "generate",
      },
      { key: "numCards", label: "Jumlah Slide/Kartu (opsional)", type: "number", min: 1, placeholder: "10" },
      {
        key: "exportAs",
        label: "Export Sebagai File",
        type: "select",
        options: [
          { label: "PPTX (PowerPoint)", value: "pptx" },
          { label: "PDF", value: "pdf" },
          { label: "PNG (zip, 1 gambar per slide)", value: "png" },
        ],
        defaultValue: "pptx",
      },
      { key: "themeId", label: "Theme ID (opsional, dari akun Gamma lo)", type: "text" },
      { key: "additionalInstructions", label: "Instruksi Tambahan buat AI (opsional)", type: "textarea" },
      {
        key: "imageSource",
        label: "Sumber Gambar",
        type: "select",
        options: [
          { label: "AI Generated (default Gamma)", value: "aiGenerated" },
          { label: "Web — bebas dipakai", value: "webFreeToUse" },
          { label: "Tanpa gambar", value: "noImages" },
        ],
        defaultValue: "aiGenerated",
      },
      {
        key: "pollTimeoutSeconds",
        label: "Maks Waktu Tunggu (detik)",
        type: "number",
        defaultValue: 180,
        placeholder: "180",
      },
    ],
  },
  "integration.supabase_storage": {
    kind: "integration.supabase_storage",
    category: "integration",
    label: "Supabase Storage",
    description: "Upload file to Supabase Storage and return public URL — isi credentials di node atau di Pengaturan Akun",
    icon: "Upload",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "supabaseUrl", label: "Supabase Project URL (opsional kalau diisi di Akun)", type: "text", placeholder: "https://xxx.supabase.co" },
      { key: "supabaseKey", label: "Supabase Key (opsional kalau diisi di Akun)", type: "password" },
      { key: "bucket", label: "Bucket Name (opsional, default: media)", type: "text", placeholder: "media" },
      {
        key: "folder",
        label: "Folder (opsional)",
        type: "text",
        placeholder: "whatsapp-uploads",
        defaultValue: "whatsapp-uploads",
      },
      {
        key: "fileUrl",
        label: "File URL (pakai {{input.mediaUrl}} atau URL langsung)",
        type: "text",
        placeholder: "{{input.mediaUrl}}",
        defaultValue: "{{input.mediaUrl}}",
      },
      {
        key: "fileName",
        label: "File Name (opsional, kosongkan = auto dari URL)",
        type: "text",
        placeholder: "video_123.mp4",
      },
    ],
  },
  "integration.media_upload": {
    kind: "integration.media_upload",
    category: "integration",
    label: "Media Upload (Cloudinary)",
    description: "Upload image/video from URL to Cloudinary — isi credentials di node atau di Pengaturan Akun",
    icon: "CloudUpload",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "cloudName", label: "Cloud Name (opsional kalau diisi di Akun)", type: "text", placeholder: "mycloud" },
      { key: "apiKey", label: "API Key (opsional kalau diisi di Akun)", type: "text", placeholder: "123456789" },
      { key: "apiSecret", label: "API Secret (opsional kalau diisi di Akun)", type: "password" },
      {
        key: "folder",
        label: "Folder (opsional, default dari Akun)",
        type: "text",
        placeholder: "zales-uploads",
      },
      {
        key: "fileUrl",
        label: "File URL (pakai {{input.mediaUrl}} atau URL langsung)",
        type: "text",
        placeholder: "{{input.mediaUrl}}",
        defaultValue: "{{input.mediaUrl}}",
      },
      {
        key: "resourceType",
        label: "Resource Type",
        type: "select",
        options: [
          { label: "Auto (detect)", value: "auto" },
          { label: "Video", value: "video" },
          { label: "Image", value: "image" },
          { label: "Raw (document)", value: "raw" },
        ],
        defaultValue: "auto",
      },
    ],
  },
  "office.excel": {
    kind: "office.excel",
    category: "office",
    label: "Generate Excel",
    description: "Build an .xlsx file from JSON data (array of rows)",
    icon: "Sheet",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "fileName", label: "File Name", type: "text", defaultValue: "laporan.xlsx" },
      { key: "sheetName", label: "Sheet Name", type: "text", defaultValue: "Sheet1" },
      {
        key: "dataJson",
        label: "Data (JSON array of rows)",
        type: "code",
        placeholder: '[\n  { "nama": "Budi", "total": 150000 },\n  { "nama": "Siti", "total": 220000 }\n]\natau pakai {{input}} kalau data datang dari node sebelumnya',
        defaultValue: "{{input}}",
      },
    ],
  },
  "office.word": {
    kind: "office.word",
    category: "office",
    label: "Generate Word",
    description: "Build a .docx document from a title + paragraphs",
    icon: "FileText",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "fileName", label: "File Name", type: "text", defaultValue: "laporan.docx" },
      { key: "title", label: "Judul Dokumen", type: "text", placeholder: "Laporan Bulanan" },
      {
        key: "content",
        label: "Isi (satu paragraf per baris)",
        type: "textarea",
        placeholder: "{{input.text}}",
      },
    ],
  },
  "office.pptx": {
    kind: "office.pptx",
    category: "office",
    label: "Generate PowerPoint",
    description: "Build a .pptx deck from a JSON list of slides",
    icon: "Presentation",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "fileName", label: "File Name", type: "text", defaultValue: "presentasi.pptx" },
      {
        key: "slidesJson",
        label: "Slides (JSON array)",
        type: "code",
        placeholder:
          '[\n  { "title": "Ringkasan", "bullets": ["Poin 1", "Poin 2"] },\n  { "title": "Penutup", "bullets": ["Terima kasih"] }\n]',
        defaultValue: "{{input}}",
      },
    ],
  },
  "integration.file": {
    kind: "integration.file",
    category: "integration",
    label: "Local File",
    description: "Read a local TXT, PDF, or JSON file",
    icon: "FileText",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "path", label: "File Path", type: "text", placeholder: "/data/input.json" },
      {
        key: "format",
        label: "Format",
        type: "select",
        options: [
          { label: "JSON", value: "json" },
          { label: "Text", value: "text" },
          { label: "PDF", value: "pdf" },
        ],
        defaultValue: "json",
      },
    ],
  },
  "integration.http": {
    kind: "integration.http",
    category: "integration",
    label: "HTTP Request",
    description: "Call an external HTTP API",
    icon: "Globe",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "url", label: "URL", type: "text", placeholder: "https://api.example.com" },
      {
        key: "method",
        label: "Method",
        type: "select",
        options: [
          { label: "GET", value: "GET" },
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
          { label: "DELETE", value: "DELETE" },
        ],
        defaultValue: "GET",
      },
      {
        key: "headers",
        label: "Headers (JSON)",
        type: "code",
        placeholder: '{\n  "X-RapidAPI-Key": "...",\n  "X-RapidAPI-Host": "google-map-scraper1.p.rapidapi.com"\n}',
        defaultValue: "{}",
      },
      { key: "body", label: "Body (JSON)", type: "code", placeholder: "{}" },
    ],
  },
  "transform.code": {
    kind: "transform.code",
    category: "transform",
    label: "Code",
    description: "Run custom JavaScript on the input data",
    icon: "Code2",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "code",
        label: "JavaScript",
        type: "code",
        defaultValue: "// input is available as `input`\nreturn input;",
      },
    ],
  },
  "transform.json": {
    kind: "transform.json",
    category: "transform",
    label: "Edit JSON",
    description: "Map or reshape fields on the data",
    icon: "Braces",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "mapping", label: "Field Mapping (JSON)", type: "code", placeholder: '{\n  "newField": "{{input.oldField}}"\n}' },
    ],
  },
  "transform.merge": {
    kind: "transform.merge",
    category: "transform",
    label: "Merge",
    description: "Combine multiple inputs into one object",
    icon: "GitMerge",
    hasInput: true,
    hasOutput: true,
    params: [],
  },
  "transform.set": {
    kind: "transform.set",
    category: "transform",
    label: "Set Fields",
    description: "Add or overwrite fields on the data passing through (like n8n's Edit Fields / Set node)",
    icon: "PenSquare",
    hasInput: true,
    hasOutput: true,
    params: [
      {
        key: "fieldsJson",
        label: "Fields to set (JSON)",
        type: "code",
        placeholder: '{\n  "status": "processed",\n  "name": "{{input.name}}"\n}',
        defaultValue: "{}",
      },
      {
        key: "keepOriginal",
        label: "Original fields",
        type: "select",
        options: [
          { label: "Keep and merge", value: "keep" },
          { label: "Replace entirely", value: "replace" },
        ],
        defaultValue: "keep",
      },
    ],
  },
  "transform.filter": {
    kind: "transform.filter",
    category: "transform",
    label: "Filter",
    description: "Stop the item here if a condition is false — downstream nodes only run for items that pass",
    icon: "Filter",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "condition", label: "Keep if (JS expression)", type: "text", placeholder: "input.value > 10" },
    ],
  },
  "logic.if": {
    kind: "logic.if",
    category: "logic",
    label: "If / Else",
    description: "Branch the workflow based on a condition",
    icon: "GitBranch",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "condition", label: "Condition", type: "text", placeholder: "input.value > 10" },
    ],
  },
  "logic.switch": {
    kind: "logic.switch",
    category: "logic",
    label: "Switch",
    description: "Route based on which of several values matches the input (multi-branch, like n8n's Switch node)",
    icon: "Split",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "valuePath", label: "Value to match", type: "text", placeholder: "input.category" },
      {
        key: "casesJson",
        label: "Cases (JSON array of strings)",
        type: "code",
        placeholder: '["urgent", "normal", "low"]',
        defaultValue: '["case1", "case2"]',
      },
    ],
  },
  "logic.wait": {
    kind: "logic.wait",
    category: "logic",
    label: "Wait",
    description: "Pause for a fixed number of seconds before continuing (capped to stay within serverless limits)",
    icon: "Clock",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "seconds", label: "Seconds to wait", type: "number", min: 1, max: 25, defaultValue: 3 },
    ],
  },
  "logic.loop": {
    kind: "logic.loop",
    category: "logic",
    label: "Loop",
    description: "Iterate over a list of items",
    icon: "Repeat",
    hasInput: true,
    hasOutput: true,
    params: [
      { key: "itemsPath", label: "Items Path", type: "text", placeholder: "input.items" },
    ],
  },
};

export const CATEGORY_LABELS: Record<string, string> = {
  trigger: "Trigger",
  ai: "AI Models",
  memory: "Memory",
  integration: "Integrations",
  transform: "Data Transformation",
  logic: "Logic",
  office: "Office / RPA",
};

export const CATEGORY_ORDER = ["trigger", "ai", "memory", "integration", "office", "transform", "logic"];

export function getNodesByCategory(): Record<string, NodeDefinition[]> {
  const grouped: Record<string, NodeDefinition[]> = {};
  for (const def of Object.values(NODE_REGISTRY)) {
    if (!grouped[def.category]) grouped[def.category] = [];
    grouped[def.category].push(def);
  }
  return grouped;
}
